language: java

jdk:
  - oraclejdk8

sudo: false

services:
  - docker

before_script: ./gradlew clean test

script: ./gradlew clean build

after_success:
  - docker build -t openvehicletracking/restapi .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push openvehicletracking/restapi
